require 'turnip/node/scenario_definition'

module Turnip
  module Node
    #
    # @note Background metadata generated by Gherkin
    #
    #     {
    #       type: :Background,
    #       location: { line: 10, column: 3 },
    #       keyword: "Background",
    #       name: "Background Description",
    #       steps: []
    #     }
    #
    class Background < ScenarioDefinition
    end
  end
end
