require 'turnip/node/scenario_definition'
require 'turnip/node/tag'

module Turnip
  module Node
    #
    # @note Scenario metadata generated by Gherkin
    #
    #     {
    #       type: :Scenario,
    #       tags: [], # Array of Tag
    #       location: { line: 10, column: 3 },
    #       keyword: "Scenario",
    #       name: "Scenario Description",
    #       steps: []
    #     }
    #
    class Scenario < ScenarioDefinition
      include HasTags
    end
  end
end
